# Generated by Django 5.1.3 on 2024-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
