# Generated by Django 5.1.3 on 2024-11-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0003_transaction_is_approved_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_approved',
        ),
    ]
