# Generated by Django 5.1.3 on 2024-11-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0004_remove_transaction_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
