# Generated by Django 5.1.3 on 2024-11-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0006_userprofile_mfa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_questions',
            field=models.JSONField(default=dict),
        ),
    ]
