# Generated by Django 5.1.3 on 2024-11-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0007_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
